connections:
  - name: 'PostgreSQL (Local)'
    type: 'postgres'
    config:
      host: 'postgres'
      port: 5432
      database: 'facet'
      user: '${FACET_POSTGRES_USER}'
      password: '${FACET_POSTGRES_PASSWORD}'
      ssl: false

  - name: 'ClickHouse (Local)'
    type: 'clickhouse'
    config:
      host: 'clickhouse'
      port: 8123
      database: 'facet'
      user: '${FACET_CLICKHOUSE_USER}'
      password: '${FACET_CLICKHOUSE_PASSWORD}'
      https: false

  - name: 'BigQuery (Samples Dataset)'
    type: 'bigquery'
    config:
      project_id: '${FACET_BIGQUERY_PROJECT_ID}'
      credentials_json: '${FACET_BIGQUERY_CREDENTIALS_JSON}'
      bigquery_dataset_project_id: 'bigquery-public-data'
      bigquery_dataset_id: '${FACET_BIGQUERY_DATASET_ID}'

  - name: 'Snowflake'
    type: 'snowflake'
    config:
      account: '${FACET_SNOWFLAKE_ACCOUNT}'
      user: '${FACET_SNOWFLAKE_USER}'
      password: '${FACET_SNOWFLAKE_PASSWORD}'
      warehouse: '${FACET_SNOWFLAKE_WAREHOUSE}'
      database: '${FACET_SNOWFLAKE_DATABASE}'
      schema: '${FACET_SNOWFLAKE_SCHEMA}'
