connections:
  - name: 'PostgreSQL (Local)'
    type: 'postgres'
    config:
      host: 'postgres'
      port: 5432
      database: 'facet'
      user: 'facet'
      password: 'facetpass'
      ssl: false

  - name: 'ClickHouse (Local)'
    type: 'clickhouse'
    config:
      host: 'clickhouse'
      port: 8123
      database: 'facet'
      user: 'default'
      password: 'clickhouse_pass'
      https: false

  - name: 'BigQuery'
    type: 'bigquery'
    config:
      project_id: 'your-project-id'
      credentials_json: '{}'

  - name: 'Snowflake'
    type: 'snowflake'
    config:
      account: 'your-account-id.snowflakecomputing.com'
      user: 'username'
      password: 'password'
      warehouse: 'compute_wh'
      database: 'your_database'
      schema: 'public'
