repos:
  # Python formatting
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        types: [python]
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        types: [python]
        additional_dependencies: [flake8-docstrings]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        files: ^backend/
        args: [--ignore-missing-imports]

  # JavaScript/React formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml]
        exclude: ^frontend/node_modules/
