services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
      - BUN_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - facet-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ./backend/config:/app/config
    ports:
      - '8000:8000'
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY:-default_secret_key_replace_in_production}
      - ALLOWED_ORIGINS=http://localhost,http://frontend
    networks:
      - facet-network

networks:
  facet-network:
    driver: bridge
