services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
      - BUN_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - facet-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ./backend/config:/app/config
    ports:
      - '8000:8000'
    environment:
      - ENVIRONMENT=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=${SECRET_KEY:-default_secret_key_replace_in_production}
      - ALLOWED_ORIGINS=http://localhost,http://frontend
    depends_on:
      - redis
    networks:
      - facet-network

  # Redis for caching
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - facet-network

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - facet-network

  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - facet-network

networks:
  facet-network:
    driver: bridge

volumes:
  redis_data:
  prometheus_data:
  grafana_data:
